# Generated by Django 3.0.5 on 2020-04-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_auto_20200410_2011"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_method",
            field=models.CharField(
                blank=True,
                choices=[("email", "Email"), ("github", "Github"), ("kakao", "Kakao")],
                default="email",
                max_length=10,
            ),
        ),
    ]
