# Generated by Django 3.0.6 on 2020-05-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_auto_20200517_2108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.ImageField(max_length=255, upload_to="room_photos"),
        ),
    ]
