# Generated by Django 3.0.5 on 2020-05-09 14:46

import core.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0008_auto_20200322_1542"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="amenity", managers=[("objects", core.managers.CustomUserManager()),],
        ),
        migrations.AlterModelManagers(
            name="facility", managers=[("objects", core.managers.CustomUserManager()),],
        ),
        migrations.AlterModelManagers(
            name="houserule",
            managers=[("objects", core.managers.CustomUserManager()),],
        ),
        migrations.AlterModelManagers(
            name="photo", managers=[("objects", core.managers.CustomUserManager()),],
        ),
        migrations.AlterModelManagers(
            name="room", managers=[("objects", core.managers.CustomUserManager()),],
        ),
        migrations.AlterModelManagers(
            name="roomtype", managers=[("objects", core.managers.CustomUserManager()),],
        ),
    ]
