# Generated by Django 3.0.5 on 2020-05-09 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0009_auto_20200509_2346"),
    ]

    operations = [
        migrations.AlterModelManagers(name="amenity", managers=[],),
        migrations.AlterModelManagers(name="facility", managers=[],),
        migrations.AlterModelManagers(name="houserule", managers=[],),
        migrations.AlterModelManagers(name="photo", managers=[],),
        migrations.AlterModelManagers(name="room", managers=[],),
        migrations.AlterModelManagers(name="roomtype", managers=[],),
    ]
