# Generated by Django 3.0.5 on 2020-05-09 14:46

import core.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_auto_20200321_2220"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="conversation",
            managers=[("objects", core.managers.CustomUserManager()),],
        ),
        migrations.AlterModelManagers(
            name="message", managers=[("objects", core.managers.CustomUserManager()),],
        ),
    ]
