# Generated by Django 3.0.5 on 2020-05-09 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0003_auto_20200509_2346"),
    ]

    operations = [
        migrations.AlterModelManagers(name="conversation", managers=[],),
        migrations.AlterModelManagers(name="message", managers=[],),
    ]
