# Generated by Django 3.0.5 on 2020-05-09 14:46

import core.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0005_auto_20200509_2013"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="bookedday",
            managers=[("objects", core.managers.CustomUserManager()),],
        ),
        migrations.AlterModelManagers(
            name="reservation",
            managers=[("objects", core.managers.CustomUserManager()),],
        ),
    ]
