# Generated by Django 3.0.4 on 2020-03-22 00:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0002_auto_20200321_2220"),
    ]

    operations = [
        migrations.RenameField(model_name="list", old_name="room", new_name="rooms",),
    ]
